### PR TITLE
Ft user profile page #157899869

### PR DESCRIPTION
**Pull request by ghost**
**What does this PR do?**
Adds the User Profile Page

**Description of Task to be completed?**
- Create a page that displays the user's profile
- Add a form where a user can change some of the details like the name and password.

**How should this be manually tested?**
Clone this repository under the **ft-User-Profile-Page-#157899881** branch and navigate to my-profile.html and open this file in your browser.

**Screenshot**
image

user-profile

**What are the relevant pivotal tracker stories?**
[#157899869](https://www.pivotaltracker.com/story/show/157899869)
[#157899881](https://www.pivotaltracker.com/story/show/157899881)

### CODE REVIEW

**Comment by Slinjez** [comment]
Nice UI, on the pt stories, I don't think [finishes] is relevant

**Comment by zakhusayn** [comment]
Great work, but don't you think the navbar is quite big for it's size

**Comment by ghost** [comment]
It is actually. I'll change that.

**Comment by johnmusiu** [comment]
Good job on the UI,

Quick question, which screenshot is for view profile page? 

PR ok, PR title a bit off as per the guidelines.

**Pull request merged**
