### PR TITLE
Feature #157815733 User Request Details

### PR DESCRIPTION
**Pull request by ghost**
**What does this PR do?**
Adds a page where the user can view all the details of a request

**Description of Task to be completed?**
- Show how information about a request will be displayed.
- Include buttons that provide users with actions such as editing, canceling and deleting a request.

**How should this be manually tested?**
Clone this repository under the **ft-User-Request-Details-#157815733** branch and navigate to user-view-request.html and open this file in your browser.

**Screenshot**
user-request-details

**What are the relevant pivotal tracker stories?**
[Finishes|Delivers [#157815733 ](https://www.pivotaltracker.com/story/show/157815733)]

### CODE REVIEW

**Comment by lawrenceChege** [comment]
Nice work. You could make either the background or the card darker to concentrate attention to one place.
right now it seems like one thing

**Comment by asamisellah** [comment]
Good design although I would kindly suggest that you use a backgroud image that conveys the context of the app.

**Comment by ghost** [comment]
Yeah... I'll do that as soon as I get one with a beige theme. I've grown fond of the color in the past week.

**Comment by lawrenceChege** [comment]
Its okay now. 
we can distinguish between the background and the card

**Comment by joelmachango** [comment]
Beautiful UI. The PR is well documented. @davenmathews

**Comment by johnmusiu** [comment]
Good job on the UI. PR looks good too

**Pull request merged**
